# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.3

# Builder stage
FROM golang:1.24-alpine AS builder

# Disable CGO for static binary
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

WORKDIR /src

# Copy go modules manifests and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Build the gospy binary
RUN go build -o /gospy .

# Final stage: minimal runtime image
FROM alpine:latest

# Copy the binary
COPY --from=builder /gospy /gospy

# Expose the MCP port (default 8974)
EXPOSE 8974

# Entrypoint: start HTTP API with MCP enabled
ENTRYPOINT ["/gospy", "serve", "--enable-mcp", "--port", "${PORT:-8974}"]
