version: '3.8'

services:
  test-server:
    privileged: true
    security_opt:
      - seccomp:unconfined
    build:
      context: ./test_server
    platform: linux/arm64
    ports:
      - "8081:8080"
    init: true
