name: Go
on:
  push:
    branches: 
      - master
jobs:

  test:
    name: e2e test on different target go version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        e2e_go_version: [1.10, 1.11, 1.12, 1.13]
    steps:

    - name: Setup e2e Go ${{ matrix.e2e_go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.e2e_go_version }}

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build target process binary
      run: go build -o testdata/test_${{ matrix.e2e_go_version }} testdata/test.go
    
    - name: Test
      run: ls testdata && go test
