name: Go
on:
  push:
    branches: 
      - master
jobs:

  test:
    name: e2e test on go(gospy:${{ matrix.gospy_go_version }},e2e:${{ matrix.e2e_go_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gospy_go_version: ["1.12", "1.13"]
        e2e_go_version: ["1.10", "1.11", "1.12", "1.13"]
    steps:

    - name: Setup e2e Go ${{ matrix.e2e_go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.e2e_go_version }}

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build target process binary
      run: go build -o testdata/test_bin testdata/test.go

    - name: Setup gospy go ${{ matrix.gospy_go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.gospy_go_version }}
    
    - name: Test
      run: go test -v
      env:
        E2E_GO_VERSION: ${{ matrix.e2e_go_version }}
