name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64 , arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.x
      - name: Build
        env:
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o gospy-linux-${{ matrix.goarch }} .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gospy-linux-${{ matrix.goarch }}
          path: gospy-linux-${{ matrix.goarch }}
  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.x
      - name: Build
        run: |
          go build -o gospy-darwin-arm64 .
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: gospy-darwin-arm64
          path: gospy-darwin-arm64
  release:
    name: Create Release
    needs:
      - build-linux
      - build-macos
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: LS artifacts
        run: ls -R
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref }}"
          files: |
            gospy-linux-amd64/gospy-linux-amd64
            gospy-linux-arm64/gospy-linux-arm64
            gospy-darwin-arm64/gospy-darwin-arm64
