name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: gospy-linux-amd64
            env:
              GOOS: linux
              GOARCH: amd64
          - os: ubuntu-latest
            artifact_name: gospy-linux-arm64
            env:
              GOOS: linux
              GOARCH: arm64
          - os: macos-latest
            artifact_name: gospy-darwin-arm64
            env:
              GOOS: darwin
              GOARCH: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        env: ${{ matrix.env }}
        run: |
          go build -o ${{ matrix.artifact_name }} .
          sha256sum ${{ matrix.artifact_name }} > ${{ matrix.artifact_name }}.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ${{ matrix.artifact_name }}
            ${{ matrix.artifact_name }}.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          files: |
            artifacts/gospy-linux-amd64
            artifacts/gospy-linux-amd64.sha256
            artifacts/gospy-linux-arm64
            artifacts/gospy-linux-arm64.sha256
            artifacts/gospy-darwin-arm64
            artifacts/gospy-darwin-arm64.sha256
